### ISSUE TITLE
执行generate-version-file 报错，报错信息如下：

### ISSUE THREAD

**Issue by wuhao-max** [guMcrey/version-rocket#30]
node_modules\_version-rocket@1.6.7@version-rocket\scripts\createVersionFile.js:13
  const externalJSONPath = process.env.EXTERNAL_PATH?.trim() ? path.join(process.cwd(), process.env.EXTERNAL_PATH.trim()) : '';
                                                     ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

这个是因为用了可选链操作符，但是我的nodejs版本是12.22.12   不知道为什么还是一直报错，作者大大可以兼容一下写法吗？改成const externalJSONPath = process.env.EXTERNAL_PATH && process.env.EXTERNAL_PATH.trim() ? path.join(process.cwd(), process.env.EXTERNAL_PATH.trim()) : '';

**Comment by wuhao-max** [comment]
不好意思，才看到了，支持node 14 以上的版本。
